import { z } from 'zod';

export const AddPlaceSchema = z.object({
    id: z.string().optional(),
    placeId: z.string().optional(),
    longitude: z.number().optional(),
    latitude: z.number().optional(),
    name: z.string().nonempty(),
    address: z.string().nonempty(),
    city: z.string().nonempty(),
    phoneNumber: z.string().optional(),
    website: z.string().optional(),
    description: z.string().nonempty(),
    openingHours: z.array(z.string()).optional(),
    imagesSelected: z.array(z.string()).optional(),
    userImages: z.any().optional(),
    espressoPrice: z.string().optional(),
    facility: z
        .enum([
            'IS_CAFE',
            'IS_HOTEL',
            'IS_LIBRARY',
            'IS_THIRD_SPACE',
            'IS_OTHER_TYPE',
        ])
        .optional(),
    hasPrivacy: z.boolean().optional(),
    hasParking: z.boolean().optional(),
    hasWiFi: z.boolean().optional(),
    hasExterior: z.boolean().optional(),
    hasPlugs: z.boolean().optional(),
    hasHandicap: z.boolean().optional(),
    smallTables: z.boolean().optional(),
    largeWorktables: z.boolean().optional(),
    counterSeats: z.boolean().optional(),
    standingTables: z.boolean().optional(),
    outdoorSeating: z.boolean().optional(),
    soloCoworker: z.boolean().optional(),
    smallGroup: z.boolean().optional(),
    bigGroup: z.boolean().optional(),
    morningDuration: z.boolean().optional(),
    afternoonDuration: z.boolean().optional(),
    fullDuration: z.boolean().optional(),
    snacksPossibility: z.boolean().optional(),
    lunchPossibility: z.boolean().optional(),
    souperPossibility: z.boolean().optional(),
    drinksPossibility: z.boolean().optional(),
    alcoolPossibility: z.boolean().optional(),
    music: z
        .enum(['NO_MUSIC', 'DISCRETE_MUSIC', 'RANDOM_MUSIC', 'LOUD_MUSIC'])
        .optional(),
    wifiQuality: z.enum(['HIGH_WIFI', 'MEDIUM_WIFI', 'LOW_WIFI']).optional(),
    reviewContent: z.string().nonempty(),
    calmRating: z.number().min(1).max(5),
    equipRating: z.number().min(1).max(5),
    foodRating: z.number().min(1).max(5),
    feelingRating: z.number().min(1).max(5),
});

export type AddPlaceSchemaType = z.infer<typeof AddPlaceSchema>;
